### ISSUE TITLE
add id attributes to meeting logs

### ISSUE THREAD

**Issue by jnewbery** [bitcoin-core-review-club/bitcoin-core-review-club.github.io#143]
I've summarized a previous Review Club meeting for the Optech newsletter (here: https://github.com/bitcoinops/bitcoinops.github.io/pull/366#issuecomment-596774687). For those summaries, it'd be really useful to be able to link specific lines in the meeting log. For that we'd need id or name attributes for each line.

@ajttowns bot does that automatically, eg http://www.erisian.com.au/bitcoin-core-dev/log-2020-03-10.html#l-3. Perhaps it's time to start doing something a bit smarter than copy-pasting meeting logs so we can add more structure to the logs.

**Comment by jonatack** [comment]
I agree and use those tags in erisian.com frequently. The markup would be easy to add:

```html
<a name="l-4"></a>
```
or also displaying line numbers:
```html
<a name="l-4"></a><span class="lineno">  4 </span>
```

It wouldn't be hard to write a rake (ruby make) task to convert existing post files to add that. Did you have another process in mind?

**Comment by jnewbery** [comment]
> Did you have another process in mind?

I hadn't really thought about implementation, but perhaps we could do this as a jekyll plugin. Take a look at https://github.com/bitcoinops/bitcoinops.github.io/blob/master/_plugins/auto-anchor.rb, which automatically adds id elements to list items in the optech newsletter. We could do something similar here for any line of code in the 'meeting logs' section.

**Comment by jonatack** [comment]
Ok, will look at getting something working this weekend.

**Comment by jonatack** [comment]
> Ok, will look at getting something working this weekend.

Err, tonight :) ... timing was a bit thrown off by the government measures here (we're now confined indefinitely)

**Comment by jnewbery** [comment]
No rush. The world's ending. Improving the PR Review Club website can wait for a bit 🙃
