### ISSUE TITLE
Color-code meeting participants

### ISSUE THREAD

**Issue by jnewbery** [bitcoin-core-review-club/bitcoin-core-review-club.github.io#156]
We render all meeting participants in the same color. A couple of people have suggested to me that each participant should have a separate color to make it easier to follow threads. Not sure how much effort it'd be to implement it or how useful in general, but I'm opening this issue to track that request.

currently:

![image](https://user-images.githubusercontent.com/1063656/77122794-ea3d5680-6a14-11ea-8f5e-adf68d898d69.png)

proposed:

![image](https://user-images.githubusercontent.com/1063656/77122989-5750ec00-6a15-11ea-9781-502ac13d72aa.png)

**Comment by jonatack** [comment]
Ok. Should be easy: start with a data structure of shuffled basic colors, then in the loop set the `nick` text color to `(the assigned color for that nick if it exists, otherwise assign one)`.

**Comment by jonatack** [comment]
Done with #157.
