### ISSUE TITLE
Add component and host indexes

### ISSUE THREAD

**Issue by jnewbery** [bitcoin-core-review-club/bitcoin-core-review-club.github.io#25]
After #21, each PR page will have a component and host tag. Add per-component and per-host index pages so interested users can look for all PRs by a component. I expect the URL scheme will be eg `https://bitcoin-core-review-club.github.io/component/wallet`, `https://bitcoin-core-review-club.github.io/host/jonatack`, etc

**Comment by jonatack** [comment]
Sounds good. I'd suggest the following route format: `/plural-path/:id-name`, e.g.  `/components/7-wallet` or  `/hosts/1-jnewbery` to anticipate index listings of all the components or hosts. (The ids are optional at this point and are habit from the idea of storing these things in a database).

If this continues, e.g. adding search and so on, it may be less and less a static website and converting it to a database-backed Ruby on Rails app at some point with an admin backend for handling tables of posts, components, or hosts might make sense.

That said, I have no other experience with static websites or Jekyll, so this might be me projecting what I previously knew well (database-backed Rails web apps with admin backends) where it isn't necessary.

**Comment by jnewbery** [comment]
Thanks for the suggestions @jonatack !

> I'd suggest the following route format: /plural-path/:id-name

Using the plural noun in the path seems reasonable and matches what we do at https://bitcoinops.org/en/newsletters/ for example. I don't think the indexes are necessary (and I'd prefer not to be `1-jnewbery` :) )

> converting it to a database-backed Ruby on Rails app ... might make sense.

I'd much prefer keeping this as a static website as long as we can. The benefits are that it's less maintenance and easier to develop against (eg it's very easy for me to do a `make preview` of this site and host it locally). It's also much easier to rehost a static website anywhere. For example, we moved the bitcoinops.org website from github pages to netlify with a few clicks. Having that kind of flexibility would be difficult with a database-backed website. Jekyll is quite powerful and has been able to handle everything we've thrown at it for the bitcoinops website, including the new compatibility site.

**Comment by jonatack** [comment]
Yes, agreed!
