### ISSUE TITLE
Clarify purpose of IRC meetings

### ISSUE THREAD

**Issue by jnewbery** [bitcoin-core-review-club/bitcoin-core-review-club.github.io#69]
@miketwenty1 mentioned that it's not immediately obvious what the purpose of the IRC is when arriving at the landing page: https://bitcoincore.reviews/. There is some rationale ("The point of the review club is to give participants..." but it's a bit vague and buried in the middle of the text).

Mike - perhaps you could suggest some alternative text?

**Comment by miketwenty1** [comment]
@jnewbery ..apologies for not see the notification on Nov22.

I'm happy with the changes you made. It is very clear and explicit now! I'm a fan of the mini FAQ up top like you've structured it.

**Comment by jnewbery** [comment]
Thanks Mike!
