### ISSUE TITLE
Gemfile missing from the repository

### ISSUE THREAD

**Issue by jonatack** [bitcoin-core-review-club/bitcoin-core-review-club.github.io#9]
The Gemfile needs to be present for `bundle install` to function. The usual practice would be to commit it in the repository.

**Comment by jnewbery** [comment]
Thanks Jon!

I've tried running this locally, and with this PR, generating the page fails to authenticate to the github API and then fails to find the CSS:

![image](https://user-images.githubusercontent.com/1063656/60733788-cb119e00-9f45-11e9-93e2-211cac003302.png)

Just running `jekyll serve` in master generates the site just fine for me.

Is it possible to remove the dependency on github?

**Comment by jonatack** [comment]
Yes, I saw that auth warning and didn't have the CSS styling, nor the favicon.ico file, but I could still run the site locally otherwise.

It would likely be best to commit your Gemfile, Gemfile.lock, CSS file, and favicon (there shouldn't be anything confidential in those files) and close #10.

**Comment by jnewbery** [comment]
I've created a minimal Gemfile and added it in #12.
