### ISSUE TITLE
Save a tagged commit of PR branch at meeting time

### ISSUE THREAD

**Issue by jnewbery** [bitcoin-core-review-club/bitcoin-core-review-club.github.io#90]
Often, the PR branch will change after we've run review club. That's bad for our archives because:

- any links to commits in the previous version of the PR branch will become dead after the branch is garbage-collected by github.
- discussion in the meeting log might not make sense in retrospect if the PR changes a lot after the meeting.

One solution is to make a fork of bitcoin at `bitcoin-core-review-club/bitcoin` and then tag the PR branch before the review club, and use that tagged branch for all links. As a tagged branch in that repo, it'll persist and the links will stay live.

**Comment by jonatack** [comment]
Hmm. Is there a PR you have in mind that changed a lot afterward? I imagine we would want to still link to the live PR in bitcoin/bitcoin to encourage reviewing it. If we don't fork, for the obsolescence reasons you mention CONTRIBUTING.md could suggest to avoid using commit links/refs in the notes and questions, and when feasible to use the most recent release branch for links to the codebase (for instance, in yesterday's notes when describing the current behaviour the links were to 0.19).

**Comment by jonatack** [comment]
My intuition is that the living aspect of the actual repo is more compelling than a museum fork ;) nevertheless you raise good points worth considering.

**Comment by jnewbery** [comment]
One example: the meeting log here: https://bitcoincore.reviews/15996.html contains a link to https://github.com/bitcoin/bitcoin/pull/15996/commits/0c39465500af5309d6ca39686634c3f1e7d58d91 - a commit which no longer exists.

**Comment by jonatack** [comment]
Right, that link in the log should be updated. I agree that it would be good to use a fork for links. Would require an addition to the contributing notes.

**Comment by jnewbery** [comment]
Done in #108
